vite-pwa/vite-plugin-pwa

- src/transformers/html.ts
If a page was loaded not from a root url (eg. `https://example.com/login`) script tries to load `sw.js` from current url like this – `https://example.com/login/sw.js`, not like this - `https://example.com/sw.js`.
> fix: fixed path to sw.js

- package.json
- src/index.ts
`tsup` doesn't allow to include `process.env.NODE_ENV` piece (literally) in output. Instead, it writes value of it. This PR changes default of `workbox.mode` to `"production"`, because that's mostly desired, than `"development"`. 
`mode: "production"` results in minified output of service worker and workbox code.
Closes #8
> fix: default workbox.mode to "production"

- src/index.ts
Injection to HTML file should consider swDest option from workbox.
Closes #11
> fix: dynamic generation of swDest injection #11

- example/package.json
- example/vite.config.ts
- package.json
- pnpm-lock.yaml
- src/index.ts
In latest version, `serviceWorker.register()` has a wrong path.
`swDest: resolve(root, ${outDir}/sw.js),` has full path including root.
`workbox!.swDest.replace(outDir, '')` only replaced outDir.
add config build base (#4) in path and fix path in `manifest.webmanifest`.
> fix: service worker register path & use config build base (#4)

- src/types.ts
I found them missing but I directly edited the types files hoping it's enough 😬
> types(manifest): add missing scope and orientation

- src/cache.ts
- src/config.ts
[relative]: https://developer.mozilla.org/en-US/docs/Web/Manifest/start_url#relative_url
This pull request makes a few changes to ensure that a Vite app using `base` doesn't require additional configuration in <kbd>vite-plugin-pwa</kbd>
- Changed `start_url` to be [relative], so that when using `base` the `start_url` is resolved correctly.
- Removed a leading slash from the navigation fallback so that it matches the exact name that is rendered in the manifest, fixing an error when the service worker is first installed:
```
WorkboxError.js:28 Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"/index.html"}]
```
Initially I thought about turning `cachePreset` into a function that receives `basePath`, and use:
```js
urlPattern: basePath,
```
but after investigating, it …
> fix: ensure using `base` does not require additional configuration

- src/html.ts
Enable user disable the insertion of import script registerSW when 'injectRegister' is set disticnt from 'inline' or 'import'.
This make the plugin be unopinated of registerSW import tag on index.html.
> fix: add import script only when it's setted

- README.md
> [In order to facilitate local development, localhost is considered a secure origin by browsers as well. ](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#setting_up_to_play_with_service_workers)
So `vite preview` worked well.
> docs: update test steps

- src/options.ts
- src/types.ts
Added some more missing types for ManifestOptions and and a catch-all at the end in case some new ones are added that this library don't document
> chore: add more options to ManifestOptions

- src/modules.ts
- include vite plugins instead of excluding them: this will prevent to break build when using other plugins on the target project (see #46 ).
- change output format to `es` instead of` cjs`.
> fix: update inject manifest build

- README.md
This PR adds to README.md the following:
- `Prompt for new content`: default option, user must call `registerWS` and `SSR/SSG` hints.
- `Auto update`: user must call `registerWS` and `SSR/SSG` hints.
- `injectManifest`: `Prompt for new content` hint.
> docs: prompt for new content, auto update and inject manifest hints

- examples/vue-basic-inject-manifest/src/App.vue
- examples/vue-basic-inject-manifest/src/my-worker.js
- examples/vue-basic-inject-manifest/src/workerImport.js
- examples/vue-router/src/App.vue
- examples/vue-router/src/my-worker.js
- examples/vue-router/src/workerImport.js
This PR includes a `web worker` similar to [vite worker playground](https://github.com/vitejs/vite/tree/main/packages/playground/worker). See [vite web workers](https://vitejs.dev/guide/features.html#web-workers).
We need to check that the builds will not fail when using `generateWS` or `injectManifest`, so I include the `web worker` on `vue-router` and `vue-basic-inject-manifest` examples.
> test: add web worker to test vite web worker plugin

- README.md
- client.d.ts
- examples/vue-router/package.json
- examples/vue-router/src/ReloadPrompt.vue
- examples/vue-router/vite.config.ts
- package.json
- src/client/build/register.ts
- src/client/build/vue.ts
- src/client/type.d.ts
- add sw register callback
- add sw register error callback
- ~~add an example for logging to console the registration on router example (`ReloadPromp.vue`)~~
- add a working example on `vue-router` (configurable on `ReloadPrompt.vue` via `@rollup/plugin-replace`)
closes #93
> feat: add service worker registration callbacks

- docs/.vitepress/theme/styles/layout.css
- docs/frameworks/vue.md
- docs/guide/generate.md
- docs/guide/periodic-sw-updates.md
- docs/workbox/generate-ws.md
- docs/workbox/index.md
- docs/workbox/inject-manifest.md
- added large code blocks with `details` + `summary` html blocks: by default collapsed
- add network first strategy to workbox `injectManifest` entry: also include network first race strategy
- fix some wording and rephrase on workbox
> docs: fix large code blocks and finish workbox entry

- docs/frameworks/svelte.md
This fixes some typos made in the Svelte doc which, upon copy pasting, would bring errors if not fixed manually.
> docs: typo

- README.md
- docs/.vitepress/config.js
- docs/.vitepress/theme/components/HomeFeatures.vue
- docs/.vitepress/theme/components/HomeHero.vue
- docs/index.md
This PR includes (@antfu review configured icons on `README.md` and `docs/index.md` features icons):
- first version of README.md
- added hero text plus: npm version, npm month downloads, link to docs and github stars
- updated features entries with icons
- deleted all configuration/sample entries
- added Typescript feature
- moved sponsors to top
- updated license including `2020-PRESENT`
- added warning on new `Usage` entry about `workbox` update: if new version will not be `0.11.0` just update to new one
- added icon to Features, Install, Usage, Full config and License (heading 2)
- `vitepress` updates:
- change hero text to include `framework-agnostic plugin`
- Included icons on features
- Added `Static Assets Handling` on features
- Update padding for feature entries (`.feature`) to …
> docs: update repo readme

- docs/.vitepress/theme/components/MdListAnchor.vue
- docs/.vitepress/theme/components/NavBar.vue
- docs/.vitepress/theme/components/NavDropdownLink.vue
- docs/.vitepress/theme/components/NavDropdownLinkItem.vue
- docs/.vitepress/theme/components/NavLink.vue
- docs/.vitepress/theme/components/NavLinks.vue
- docs/.vitepress/theme/components/Page.vue
- docs/.vitepress/theme/components/SideBar.vue
- docs/.vitepress/theme/components/ToggleSideBarButton.vue
- docs/.vitepress/theme/styles/layout.css
- docs/.vitepress/theme/styles/sidebar-links.css
- docs/deployment/index.md
- docs/examples/index.md
- docs/examples/react.md
- docs/examples/svelte.md
- docs/examples/vue.md
- docs/frameworks/index.md
- docs/guide/index.md
- docs/guide/inject-manifest.md
- docs/workbox/index.md
- changed all markdown lists items using new `MdListAnchor.vue` wrapped with `ul` to increase clickeable area: also resolves seo mobile anchors issues.
- updated all media queries to use 780px instead 720px to avoid nav links overlap with the nav title when changing size
- fix for nav links when included on left menu: right now, entries cannot be expanded with mouse: missing `:class="{ open }"` on `NavDropdownLink.vue`.
> docs: fix seo mobile anchors and nav links for mobile

- docs/guide/static-assets.md
> docs: add workbox `globPatterns` usage warning on static assets guide

- src/options.ts
When using `generateWS` strategy, this PR configures `workbox.sourcemap` with `build.sourcemap` vite option:
- if `workbox.sourcemap` is configured, its value is not changed
- otherwise, if `build.sourcemap` vite option is `true`, `inline` or `hidden` then `workbox.sourcemap` is set to `true` otherwise to `false` 
**NOTE**: the default `build.sourcemap` vite option value is `false`, while the default `workbox.sourcemap` option value is `true`. With this PR, we have aligned both.
> feat: use vite `build.sourcemap` to configure `workbox sourcemap`

- docs/.vitepress/theme/components/CleanupOutdatedCaches.md
- docs/.vitepress/theme/components/GenerateSWCleanupOutdatedCaches.md
- docs/.vitepress/theme/components/InjectManifestCleanupOutdatedCaches.md
- docs/.vitepress/theme/components/MdListAnchor.vue
- docs/.vitepress/theme/components/SsrSsg.md
- docs/examples/index.md
- docs/frameworks/index.md
- docs/guide/auto-update.md
- docs/guide/inject-manifest.md
- docs/guide/prompt-for-update.md
- add cleanup outdated caches for `generateSW` and `injectManifest` strategies
- add `md` components for `cleanup outdated caches` and for `ssr/ssg`: we reuse them on `md` pages
- modify `MdListAnchor` component to add the external image after the `link slot`
- keep all frameworks ordered, that is, all mentions or lists will be always with this order: `Vue`, `React`, `Svelte` and `VitePress`.
> docs: review 3

- docs/.vitepress/theme/components/GenerateSWSourceMap.md
- docs/.vitepress/theme/components/InjectManifestSourceMap.md
- docs/guide/auto-update.md
- docs/guide/inject-manifest.md
- docs/guide/prompt-for-update.md
- service worker source map for `generateSW` strategy: for `prompt` and `autoUpdate` register types
- service worker source map for `injectManifest` strategy
@antfu For `injectManifest` strategy there is no way to generate the service worker source map only, excluding the app, since the source map is generated from the plugin using rollup using the vite `build.sourcemap` option, maybe we can add an option to generate it but not for the entire app.
>  docs: add generate sw source map 

- docs/guide/faq.md
- src/log.ts
- split assets size limit for each strategy
- cleanup some unsed `chalk` entries from log module
> docs: include inject manifest assets limit

- docs/frameworks/solidjs.md
- examples/solid-router/src/ReloadPrompt.tsx
- examples/solid-router/src/app.tsx
The SolidJS core team likes to promote the use of `<Show>` component with the fallback attribute as a more expressive way of displaying elements. I made a small revision to this example. Thanks for including SolidJS in the examples, it's quite helpful.
BTW we're using vite-plugin-pwa on solidjs.com =)
> docs(solid-js): promote Show component usage rather than ternary

- docs/.vitepress/config.js
This PR adds the fraweworks to head keywords meta to allow crawlers find this plugin.
closes #169
> docs: add frameworks to keywords

- src/client/build/react.ts
It seems service worker registration is being called multiple times preventing workbox window to work correctly.
@antfu Don't release yet, I'm fixing also `preact`, from github I don't know how to modify 2 files in the same PR.
closes #171
> fix(react): `registerSW` inside `useState`

- src/client/build/preact.ts
It seems service worker registration is being called multiple times preventing workbox window to work correctly.
closes #174
> fix(preact): `registerSW` inside `useState`

- docs/guide/faq.md
- src/html.ts
- src/options.ts
- src/types.ts
fix #178 
Verified it works in the vue example as requested in https://github.com/antfu/vite-plugin-pwa/issues/178#issuecomment-982097744.
Not sure if I was supposed to leave the change to the PWA config (`useCredentials: true`) in `examples/vue-router/vite.config.ts` so I didn't commit it for now, but that's a quick change.
> feat: support useCredentials option to enable crossorigin attribute

- src/types.ts
adds `id` to ManifestOptions so that I can set an id without getting a typescript error
https://www.w3.org/TR/appmanifest/#id-member
> feat: add `id` to manifest type

- docs/scripts/build.ts
- scripts/run-examples.ts
- src/index.ts
- src/options.ts
- src/types.ts
@antfu also included `disabled` option on `VitePluginPWAAPI` to use it on `vite-ssg`, once approved this PR and released I'll provide another PR there (see last commit). 
This PR also fix the `includeManifestIcons` option on `VitePWAOptions`.
closes #190
> feat: add disable option for sw generation and registration

- docs/.vitepress/theme/components/GenerateSWCleanupOutdatedCaches.md
- docs/.vitepress/theme/components/GenerateSWSourceMap.md
- docs/guide/generate.md
- docs/guide/index.md
For some reason there are some typos in example configs
> docs: fix typos in example configs

- docs/deployment/apache.md
- docs/deployment/netlify.md
- docs/deployment/nginx.md
- docs/guide/development.md
bellow → below
Adapted wording from "Configure `manifest.webmanifest` mime type"
in `nginx.md` because it is more instructive than in `netlify.md`.
"everything in ... as everything"
becomes
"files in ... as everything"
> docs: Fix spelling and improve wording

- docs/deployment/netlify.md
instead of `_headers` file.
This method simplifies deployment. One config file is better than two.
This method also allows for more structured configuration & additional
capabilities, as described in the Netlify configuration file syntax.
> docs: Use `netlify.toml` for Cache-Control

- docs/guide/static-assets.md
Ref: https://developer.chrome.com/docs/workbox/reference/workbox-build/#property-GlobPartial-globPatterns
Using `**.{js,css,html}` will not cache any js or css file. It must be `**/*.{js,css,html}`
> docs: fix default globPatterns

- docs/deployment/index.md
Fix typo
AWS Amplity -> AWS Amplify
> docs: update AWS Amplify errata on deployment

- docs/.vitepress/config.ts
- docs/guide/static-assets.md
- docs/workbox/generate-sw.md
- docs/workbox/index.md
- docs/workbox/inject-manifest.md
Some parts of the documentation have `generateWS` which should be `generateSW`
> docs: fix generateSW typo

- src/modules.ts
I was thinking that vite's starting up time was slow in [my project](https://github.com/traPtitech/traQ_S-UI/).
I digged down a bit and found that evaluating `workbox-build` was making it slow.
This PR changes `workbox-build` to be lazy loaded.
Since `workbox-build` is not always used, I think it is ok to do this.
Without this PR, my project takes about 1300 - 1500ms to start up.
With this PR, it takes about 500 - 600ms.
These values are obtained from output with `DEBUG="vite:config" npm run dev` like `bundled config file loaded in 565.03ms +0ms`.
> perf: lazy load workbox-build to reduce config loading time

- src/constants.ts
- src/index.ts
- src/modules.ts
- src/options.ts
- src/types.ts
- add `commonjs` and `vite:json`
- exports `defaultInjectManifestVitePlugins` from `constants.ts` module
- adds support to configure Vite plugins on `injectManifest` when building using Rollup
supersedes #215 
supersedes #261
closes #260
> feat(injectManifest): allow configure Vite plugins

- README.md
> docs: typo on commonjs plugin name

- docs/guide/development.md
I was trying to register the sw in dev mode when usng injectmanifest, and it took me a long time to figure out how, because this part of the doc was not plain enough.  Hopefully this change will make it easier.
> docs: minor improvement to docs/guide/development

- docs/guide/development.md
- examples/preact-router/src/claims-sw.ts
- examples/react-router/src/claims-sw.ts
- examples/solid-router/src/claims-sw.ts
- examples/svelte-routify/src/claims-sw.ts
- examples/sveltekit-pwa/src/app.html
- examples/sveltekit-pwa/src/claims-sw.ts
- examples/vue-router/src/claims-sw.ts
- package.json
- pnpm-lock.yaml
- src/dev.ts
- src/html.ts
- src/index.ts
I forgot to use `webManifestUrl` also on `injectDevManifest`: if someone using it will not work (`SvelteKit`  will not fail since the `manifest.webmanifest` is included on the `_layout`)
> feat: use `webManifestUrl` on `injectDevManifest`

- src/api.ts
If calling `generateBundle` api from a script, it will throw an error since there is no check if the bundle is there.
> fix: error when calling `_generateBundle` api

- src/plugins/dev.ts
In some cases, projects are behind a reverse proxy even in dev mode. The virtual dev module should respect the `base` option from vite config.
> fix: respect base path in virtual development SW

- src/types.ts
This PR adds `file_handlers` option to `ManifestOptions` interface so that Typescript would accept this option if supplied in `VitePWA` function call. Without that the `file_handlers` work, but require workaround such as `// @ts-ignore`.
The Typescript interface is rather simple inspired by `icons` options.
`file_handlers` feature description can be found here https://web.dev/file-handling/.
The purpose of this PR is to avoid `// @ts-ignore` in `vite.config.ts` when defining file handlers.
> feat: add file_handlers support to webmanifest

- docs/guide/development.md
- docs/guide/index.md
- examples/preact-router/src/claims-sw.ts
- examples/react-router/src/claims-sw.ts
- examples/solid-router/src/claims-sw.ts
- examples/svelte-routify/src/claims-sw.ts
- examples/sveltekit-pwa/src/claims-sw.ts
- examples/vue-router/src/claims-sw.ts
- src/plugins/dev.ts
- src/types.ts
This PR will use `allowlist` when creating the sw in development and deprecates the `webManifestUrl`:
- add `webManifestUrl` deprecation
- include the `navigateFallbackAllowlist` with the default
- update the development entry in docs
@antfu when reviewed and merged you can publish a new version `0.12.4`.
closes #346
supersedes #332
> feat: use `allowlist` in dev sw

- src/html.ts
The latest version `v0.12.4` added some dev specific logic in the `generateSimpleSWRegister` method to generate the `registerSW.js` file.
The `swType` isn't wrapped in quotation marks, so you see an error, e.g. `Uncaught ReferenceError: classic is not defined`.
This PR just adds the quotation marks.
> fix: escape swType when generating registration file

- src/plugins/dev.ts
When using injectManifest strategy with `injectRegister` auto or script, the `registerSW.js` not being served by the dev plugin.
closes #368
> fix(dev): missing `registerSW.js` with `injectManifest` strategy

- src/client/build/register.ts
> feat: load workbox window with dynamic import

- src/api.ts
The `webmanifest` is not generated in `SSR` and it should be generated always.
Also returning the info when required: otherwise we return always the info with the hint about the register sw (inlined or registerSW).
> fix(api): return pwa info when required

- docs/.vitepress/contributors.ts
- docs/.vitepress/theme/components/HomePage.vue
Add missing social links, the social names are there but VitePress sfc requires the links
> docs: core team social links

- src/plugins/dev.ts
request for `registerSW.js` and `workbox-*.js` is 404 when vite `base` option is not empty.(eg `/pdf-annotate/`)
> fix(dev): 404 workbox-*.js when base option exists

- package.json
- pnpm-lock.yaml
- src/modules.ts
We don't support `mode` when injectManifest strategy.
The workbox-build doesn't support it. ref: https://github.com/GoogleChrome/workbox/issues/2588
But it can enable logs and some opt-in features.
This PR is refer to https://github.com/modernweb-dev/web/blob/master/packages/rollup-plugin-workbox/README.md#a-note-on-the-mode-config-property and https://github.com/chromeos/static-site-scaffold-modules/blob/main/modules/rollup-plugin-workbox-inject/README.md#rollupconfigjs
> feat: support mode when injectManifest

- package.json
- pnpm-lock.yaml
- src/modules.ts
Tested with examples/vite-svelte example, without this it fails with the error on linked issue
EDIT: also tested `injectManifest` with vue/react/preact/solid examples
closes #405
> fix: use `createRequire` to load rollup replace plugin

- src/options.ts
By default `dontCacheBustURLsMatching` is using Vite assets file names (`<name>.<hash>.<ext>`) and  it will change to align it with Rollup default assets naming (`<name>-<hash>.<ext>`): https://github.com/vitejs/vite/pull/10878.
This PR just changes the regex to support both layouts.
> feat: support rollup assets file names

- client.d.ts
- docs/.vitepress/components.d.ts
- docs/.vitepress/theme/components/HeuristicWorkboxWindow.md
- docs/examples/preact.md
- docs/examples/react.md
- docs/examples/solidjs.md
- docs/examples/svelte.md
- docs/examples/sveltekit.md
- docs/examples/vue.md
- docs/frameworks/preact.md
- docs/frameworks/react.md
- docs/frameworks/solidjs.md
- docs/frameworks/svelte.md
- docs/frameworks/vue.md
- docs/guide/development.md
- docs/guide/periodic-sw-updates.md
- src/client/build/register.ts
I have tested this PR using `pnpm run build && pnpm run examples` using vue example with 2 chrome instances, first one with 2 tabs. Once I refresh one app, the reload prompt will be shown on other tab/instance and once reload the app, the 3 clients are updated (the prompt dialog also gone on the 3 clients).
EDIT: once installed on the 3 clients, stop the server and run `pnpm run examples` again with the same configuration and refresh the page on 1 client.
We need to test it on Firefox and Safari on others OS: only tested on Windows 10 PRO.
/cc @develohpanda 
closes #393
> fix(client): multiple clients with prompt for update

- docs/scripts/pwa.ts
Since the rdirection to the new docs is already configured, we only need to add `selfDestroying` to the docs here, then on reload and once the pwa is deleted from the client, users will be redirected to the new docs.
This PR will be on draft until I merge and publish `v0.13.4` with my 3 last pending PR and the integrations also released.
We need to add a new entry in the new docs repo about the pwa info virtual module, I'll send a PR later.
Once we have `v0.13.4` and the integrations, we can merge this PR, we shouldn't remove the docs from here, but we need to freeze it (we also need to keep it on netlify or ppl won't be able to uninstall the old PWA, maybe in a future we can remove it also from netlify).
/cc @antfu  (sorry for the ping)
> docs: unregister docs from the plugin repo

- src/types.ts
Add [share_target](https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target)~~, `files` will be an array~~.
> feat: add share_target to manifest

- examples/vanilla-ts-dev-options/package.json
- examples/vanilla-ts-dev-options/vite.config.ts
- examples/vanilla-ts-no-ip/vite.config.ts
- src/modules.ts
This PR also replaces `'__SW__'` with `buildBase`, if missing it is initialized with `baseBuild`, check https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/options.ts#L161
> fix: use build base on virtual module

- package.json
If typescript uses "exports" field for resolution, it will ignore all other resolutions, so I have this error with the `bundler` `moduleResolution`:
```
error TS2688: Cannot find type definition file for 'vite-plugin-pwa/client'.
The file is in the program because:
Entry point of type library 'vite-plugin-pwa/client' specified in compilerOptions
tsconfig.json:9:7
9       "vite-plugin-pwa/client"
~~~~~~~~~~~~~~~~~~~~~~~~
File is entry point of type library specified here.
```
https://arethetypeswrong.github.io
> fix: support "types" condition in "exports" field

- src/types.ts
Fixes https://github.com/vite-pwa/vite-plugin-pwa/issues/509
> fix: Make manifest.shortcuts.icons optional #509

- examples/vue-router/vite.config.ts
- scripts/build.ts
- scripts/dev.ts
- scripts/run-examples.ts
- src/options.ts
- src/plugins/dev.ts
- src/types.ts
Requires enable `devOptions.suppressWarnings = true`.
closes #436
> feat: Allow suppress workbox-build warnings in dev

- src/types.ts
Scope extensions are currently part of the manifest incubation: https://github.com/WICG/manifest-incubations/blob/gh-pages/scope_extensions-explainer.md
> feat(types): allow `scope_extensions`

- src/types.ts
`narrow` and `wide` are specified to be part of `form_factor`, not `platform`: https://w3c.github.io/manifest-app-info/#form_factor-member
> feat: add missing `screenshots.form_factor` and fix wrong `screenshots.platform` options

- examples/preact-router/package.json
- examples/preact-router/tsconfig.json
- examples/preact-router/tsconfig.node.json
- examples/react-router/package.json
- examples/react-router/tsconfig.node.json
- examples/solid-router/package.json
- examples/solid-router/src/vite-env.d.ts
- examples/solid-router/tsconfig.json
- examples/solid-router/tsconfig.node.json
- examples/svelte-routify/tsconfig.json
- examples/svelte-routify/tsconfig.node.json
- examples/vanilla-ts-dev-options/package.json
- examples/vanilla-ts-dev-options/tsconfig.json
- examples/vanilla-ts-no-ip/package.json
- examples/vanilla-ts-no-ip/tsconfig.json
- examples/vue-basic-cdn/package.json
- examples/vue-basic-cdn/tsconfig.json
- examples/vue-basic-cdn/tsconfig.node.json
- examples/vue-router/package.json
- examples/vue-router/src/vite-env.d.ts
- examples/vue-router/tsconfig.json
- examples/vue-router/tsconfig.node.json
- package.json
This PR includes the tsconfig from create-vite (tsconfig.node.json + tsconfig.json updates) using bundler and updating all examples to use type module.
It took a while testing all examples including CJS.
> chore: update examples including tsconfig and type module

- examples/vue-router/vite.config.ts
- src/options.ts
- src/types.ts
Some updates to `manifest` option
1. `icons` member
https://developer.mozilla.org/en-US/docs/Web/Manifest/icons
https://w3c.github.io/manifest/#icons-member
https://w3c.github.io/manifest/#manifest-image-resources
2. `display` member
https://developer.mozilla.org/en-US/docs/Web/Manifest/display
https://w3c.github.io/manifest/#display-member
3. `display_override` member
https://developer.mozilla.org/en-US/docs/Web/Manifest/display_override
https://wicg.github.io/manifest-incubations/#display_override-member
4. `file_handlers` member
https://developer.mozilla.org/en-US/docs/Web/Manifest/file_handlers
https://wicg.github.io/manifest-incubations/#file_handlers-member
5. `shortcuts.icons` member
https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts …
> feat: update type definitions for `manifest` options

- package.json
- src/modules.ts
This PR also includes:
- check if the client is a `WindowClient` before calling `navigate`, it can be `Push/Sync`  worker (missing `navigate` method)
- bump to pnpm 8.11.0
closes #560
> fix: remove sw cache storage entries when using self destroying option

- src/options.ts
Fixes one line conditional enabling collection of static assets.
Currently `includeAssets` option has no effect unless `manifest` is also set. This makes it impossible to include additional assets while managing your own manifest file.
> Run configureStaticAssets when includeAssets option is true regardless of manifest option.

- src/types.ts
This enables autocompletion for possible values of the IconResource `purpose` field, yet allowing for arbitrary values.
> types: autocomplete `purpose` in IconResource

- src/client/build/register.ts
I've seen the the dynamic import for workbox fail on older browsers, see #645. This PR adds basic error handling to ignore the workbox setup in such situations.
Fixes #645.
> Add error handling to workbox import.

- src/client/build/register.ts
After some digging we finally fixed the problem with external sw and prompt:
- open page in a new tab and navigate to home page
- add a new sw version
- open a new second tab and navigate to home page
- click reload on the first tab
- second tab refreshed, but the first tab doesn't (still with prompt)
**NOTE**: this PR should be included in next `v0.18.0` minor release.
> fix: register client module and prompt

- src/options.ts
- src/types.ts
Changed start_url to start_url + '?standalone=true'
> Small fix to match info in types.ts

- src/plugins/dev.ts
> fix(dev): inject register not working when disabling web manifest

- src/options.ts
- src/types.ts
- src/vite-build.ts
- allow configure `envOptions`  to build the service worker 
- allow the integrations to customize the Vite build options
Check https://github.com/vite-pwa/astro/issues/42
related #689
> feat(injectManifest): add sw build env options and allow change vite configuration

- examples/assets-generator/package.json
- examples/preact-router/package.json
- examples/react-router/package.json
- examples/solid-router/package.json
- examples/svelte-routify/package.json
- examples/vanilla-js-custom-sw/package.json
- examples/vanilla-ts-no-ip/package.json
- examples/vue-router/package.json
- package.json
- pnpm-lock.yaml
`workbox-google-analytics` has been deprecated, it is not compatible with newer Google Analytics v4: https://developer.chrome.com/docs/workbox/modules/workbox-google-analytics/
```shell
pnpm ls --depth Infinity @rollup/plugin-node-resolve
Legend: production dependency, optional only, dev only
vite-plugin-pwa@0.19.8 D:\work\pwa\vite-plugin-pwa-main
dependencies:
workbox-build 7.1.0
└── @rollup/plugin-node-resolve 15.2.3
```
supersedes #592
> fix(workbox)!: update workbox dependencies to 7.1.0

- package.json
- pnpm-lock.yaml
- src/assets.ts
https://npmgraph.js.org/?q=fast-glob - 17 dependencies
https://npmgraph.js.org/?q=tinyglobby - 2 dependencies
> chore: switch to tinyglobby to drop 15 dependencies

- examples/vue-router/vite.config.ts
- src/log.ts
- src/modules.ts
- src/options.ts
- src/types.ts
- src/vite-build.ts
closes #458
closes #717
---
> [!TIP]
> feat: throw error when `maximumFileSizeToCacheInBytes` found in sw build warnings

- package.json
- pnpm-lock.yaml
- src/api.ts
- src/context.ts
- src/log.ts
- src/modules.ts
- src/vite-build.ts
- use `readFileSync`  to load version
- add `./package.json` to package exports
- update `debug`  to `4.3.6`
- update `@vite-pwa/assets-generator` to `0.2.6`
- load `workbox` when using `injectManifest` strategy only when there is injection point
- change `maximumFileSizeToCacheInBytes` error message, check screenshots below
closes #749
_generateSW strategy error_
_injectManifest strategy error_
---
> [!TIP]
> feat(injectManifest): optimize workbox load

- src/plugins/dev.ts
Missing version when generating the sw with dev options enabled.
---
> [!TIP]
> fix: dev sw stop working when using generateSW strategy

- docs/package.json
- package.json
- pnpm-lock.yaml
- src/modules.ts
This PR also includes:
- fix Rollup build XSS vulnerability (CVE-2024-43788): removed `rollup` from dev dependencies adding it to "pnpm.overrides"
- use `node:module` to fix `Dynamic require of "workbox-build"` error
With this PR the plugin can still be used with Vite 3.
supersedes #759
resolves #667
resolves #758
---
> [!TIP]
> feat!: update workbox to 7.3.0

- src/client/build/register.ts
At given point `event.isExternal` has already been evaluated to be `undefined`
https://github.com/vite-pwa/vite-plugin-pwa/blob/bee73adb56f3f08434981c022ecd5657d040ed55/src/client/build/register.ts#L94
so it's value cannot be truthy.
none
I'm just trying to understand how the client-side logic works
> chore: Remove dead code

- src/client/build/register.ts
Event has been removed in workbox 6: https://developer.chrome.com/docs/workbox/migration/migrate-from-v5
Context: https://github.com/googlechrome/workbox/issues/2786
none
Continuation of https://github.com/vite-pwa/vite-plugin-pwa/commit/c3a0710ee119995cb08d975c9f28f4e9f5df9ecb
> chore: remove listener for non-existing `externalwaiting` event

- src/html.ts
- src/pwa-assets/html.ts
When there is no `head` in the html entry point, the sw and the web manifest may not be register: this PR checks for `</head>`  and `<body>` to add the head when required, showing a warning when missing both.
resolves #782
---
> [!TIP]
> feat(html): add head when missing from entry point

- src/options.ts
- src/types.ts
Fixes an issue where the default description in the web app manifest was not being populated from the `package.json` file, despite the type definition indicating this behavior. This change ensures that if no explicit description is provided in the plugin options, the description from the project's `package.json` will be used as the default, aligning with the documented type definition in `types.ts`. This improves consistency and reduces the need for developers to duplicate the description in multiple places.
```typescript
export interface ManifestOptions {
/**
* @default _npm_package_name_
*/
name: string
/**
* @default _npm_package_name_
*/
short_name: string
/**
* @default _npm_package_description_
*/
description: string
/**
```
This change brings the runtime behavior in line with the …
> fix(manifest): default description need to come from package

- examples/preact-router/src/ReloadPrompt.tsx
- examples/react-router/src/ReloadPrompt.tsx
- examples/solid-router/src/ReloadPrompt.tsx
- examples/svelte-routify/src/lib/ReloadPrompt.svelte
- examples/sveltekit-pwa/src/lib/components/ReloadPrompt.svelte
> chore: remove usage of deprecated `reloadPage` param in examples

- src/api.ts
- src/plugins/build.ts
- src/types.ts
[Assigning to `bundle` object is discouraged by rollup](https://rollupjs.org/plugin-development/#generatebundle:~:text=DANGER,this.emitFile.) and is not supported by rolldown.
This PR changes the code using assignment to use `this.emitFile` instead. This would make vite-plugin-pwa work with Rolldown powered Vite.
If the plugin context is not passed to `api.generateBundle`, it will still use the previous method for backward compat.
---
> [!TIP]
> fix: avoid assigning to bundle object

- src/options.ts
- src/types.ts
Warning in chrome 139.0.7258.66
`manifest.webmanifest:1 Manifest: scope_extensions entry ignored, required properties 'type' and 'origin' are missing.`
Fixes https://github.com/vite-pwa/vite-plugin-pwa/issues/879
I made the property optional since 'origin' is the only allowed type and there shouldn't be a breaking type change for such a minor issue. Therefore, I don't yet see the value in documenting it. If you'd like me to update some docs, let me know!
> fix: add origin to scope_extensions to comply with the spec and get rid of warning
