vite-pwa/vite-plugin-pwa

- pnpm-lock.yaml
- src/index.ts
- src/types.ts
fix-5: Make dist folder configurable
> feat: new config for outDir, close #5

- example/package.json
- example/public/sw.js
- example/vite.config.ts
- pnpm-lock.yaml
- src/config.ts
- src/html.ts
- src/index.ts
- src/types.ts
> feat: add injectManifest strategies

- src/config.ts
- src/html.ts
- src/index.ts
- src/types.ts
Minify the generated manifest to save some bytes
> feat: new minify option

- src/html.ts
- src/index.ts
- src/options.ts
- src/types.ts
> feat: add option to disable manifest generate, close #48

- README.md
- src/modules.ts
> chore: cleanup WIP icons generation from docs and plugin from `injectManifest` build

- package.json
> deps: add workbox window and workbox build as peer dependencies

- docs/.vitepress/config.js
- docs/deployment/apache.md
- docs/deployment/index.md
- docs/deployment/nginx.md
- docs/examples/index.md
- docs/examples/react.md
- docs/examples/svelte.md
- docs/examples/vitepress.md
- docs/examples/vue.md
- docs/frameworks/index.md
- docs/frameworks/react.md
- docs/frameworks/svelte.md
- docs/frameworks/vitepress.md
- docs/frameworks/vue.md
- docs/guide/testing.md
- docs/public/_headers
- Frameworks:
- Vite: includes custom vite virtual modules references
- Svelte: modified to use `svelte` virtual module
- React: included using `react` virtual module
- Examples: new entry
- Vue 3
- React
- Svelte
- Vitepress
- Deployment:
- Added entry `Testing your application on production`
- Included `NGINX` configuration
- Include configuration file name for `Apache`
> docs: review 1

- docs/.vitepress/theme/Layout.vue
- docs/.vitepress/theme/components/GenerateSWCleanupOutdatedCaches.md
- docs/.vitepress/theme/components/HeuristicWorkboxWindow.md
- docs/examples/react.md
- docs/examples/svelte.md
- docs/examples/vue.md
- docs/frameworks/react.md
- docs/frameworks/svelte.md
- docs/frameworks/vue.md
- docs/guide/periodic-sw-updates.md
- docs/package.json
- pnpm-lock.yaml
- Hides the side bar menu on mobile when click outside: added `@vueuse/shared` to use `useDebounceFn`
- fix strategy with `generateSW` instead `prompt` on `GenerateSWCleanupOutdatedCaches` component
@antfu Just review it, I'll merge (all logic on `Layout` component).
> docs: add click outside on side bar menu for mobile

- docs/guide/sw-registration-errors.md
this PR includes:
- fix of typo in sw-registration-errors.md
> docs: fixed typo in sw-registration-errors

- README.md
> docs: add `solid-js` and `preact` and link for client type declarations

- src/options.ts
> feat: optimize workbox work

- docs/deployment/nginx.md
Added more details about common pitfalls, as learned from #177.
> docs: update to NGINX docs

- docs/guide/faq.md
router.isReady() method is async and doesn't accept any args.
> docs: fix register pwa with router on FAQ

- docs/workbox/inject-manifest.md
> docs: add link to `yt-playlist-notifier` repo

- src/assets.ts
- src/types.ts
https://w3c.github.io/manifest/#processing-image-resources
breaking change?
closes #216
> fix: shortcuts icons type on pwa manifest

- CONTRIBUTING.md
the build error is fixed on #285
> docs: include testing docs on contributing

- docs/workbox/index.md
Thank you for this great Vite plugin. As I was reading through the docs, I found some pieces a little hard to read and follow. So this is my first contribution which is a bit of a rewrite of the content to improve readability. Please let me know your thoughts.
> Update for improved readability

- docs/guide/unregister-service-worker.md
- ~~add warning, not yet available~~
- updates the danger section
> docs: update unregister pwa entry

- docs/.vitepress/theme/styles/main.css
- docs/.vitepress/theme/styles/vars.css
Just compare current code blocks with the preview.
> docs(fix): lang and copy in code blocks in light mode

- src/modules.ts
- src/options.ts
- src/types.ts
This PR should go to current main branch.
closes #372
> feat: add support for iife build format

- README.md
- docs/.vitepress/config.ts
- docs/deployment/index.md
Just a small update to fix all the broken links still pointing to the old docs url
> docs: updates all links to docs to the new url

- src/options.ts
> perf: calculate asset hash when required

- src/plugins/dev.ts
https://github.com/vite-pwa/nuxt/issues/46
> fix: dev plugin and base url

- src/modules.ts
> fix: Add vite resolve option when building custom sw

- src/types.ts
This PR includes new manifest options:
- [handle_links](https://github.com/WICG/pwa-url-handler/blob/main/handle_links/explainer.md#handle_links-manifest-member)
- [launch_handler](https://developer.mozilla.org/en-US/docs/Web/Manifest/launch_handler#launch_handler_item_values)
- [edge_side_panel](https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/sidebar#enable-sidebar-support-in-your-pwa)
> feat: add new manifest options

- src/plugins/build.ts
- src/plugins/dev.ts
`enforce`/`transform` of transformIndexHtml hook is deprecated since Vite 4. Also an runtime warning is added in Vite 5.
This PR changes that to use `order`/`handler` instead for Vite 4+.
> refactor: use `order`/`handler` for transformIndexHtml

- examples/vanilla-ts-dev-options/package.json
- info.d.ts
- src/api.ts
- src/html.ts
- src/plugins/info.ts
- src/types.ts
> fix: expose `injectRegister` in pwa info

- src/plugins/dev.ts
> fix: handle Vite's base properly in dev server

- src/client/build/register.ts
This PR reverts [#663 PR](https://github.com/vite-pwa/vite-plugin-pwa/pull/633) , prompt not being shown and the sw being auto updated under some conditions we need to investigate.
closes #663
> fix: revert PR 633

- src/client/build/register.ts
> fix: wrong changes reverting prompt logic

- examples/assets-generator/package.json
- examples/assets-generator/vite.config.ts
- examples/vanilla-js-custom-sw/package.json
- package.json
- src/pwa-assets/options.ts
> fix: pwa assets disabled when using inlined configuration

- src/plugins/dev.ts
> fix(dev): custom service worker with custom base not working

- package.json
- pnpm-lock.yaml
> chore: bump pnpm to latest v9

- .github/pull_request_template.md
- .github/workflows/cr-comment.yml
- .github/workflows/cr.yml
- add PR template
- add CR comment workflow via `/publish` (tip on the PR template)
- add CR workflow to use `/publish`  comment
/cc @Aslemammad
> chore: add `pkg.pr.new`

- package.json
- pnpm-lock.yaml
Wrong version used in #781 
---
> [!TIP]
> chore: update rollup version in `pnpm.overrides`

- package.json
- src/api.ts
https://github.com/vitejs/vite/releases/tag/v6.0.0
> feat: support Vite 6

- examples/assets-generator/package.json
- examples/preact-router/package.json
- examples/react-router/package.json
- examples/solid-router/package.json
- examples/vanilla-js-custom-sw/package.json
- examples/vanilla-ts-no-ip/package.json
- examples/vue-router/package.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
This PR also add sharp 0.33.5 to pnpm `onlyBuiltDependencies`.
---
> [!TIP]
> feat!: update `@vite-pwa/assets-generator` to `v1.0.0`

- src/pwa-assets/config.ts
> feat(pwa-assets): add additional checks to resolve images
